"""initial schema

Revision ID: b6db52ad4bed
Revises: 
Create Date: 2026-03-26 05:04:58.523416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6db52ad4bed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('canonical_url', sa.String(length=512), nullable=False),
    sa.Column('original_url', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('metro', sa.String(length=255), nullable=True),
    sa.Column('contact_url', sa.String(length=512), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'hidden', name='instancestatus'), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'unlisted', name='instancevisibility'), nullable=False),
    sa.Column('reporting_mode', sa.Enum('none', 'heartbeat', 'stats', name='reportingmode'), nullable=False),
    sa.Column('auth_token_hash', sa.String(length=255), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('software_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes_internal', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instances_canonical_url'), 'instances', ['canonical_url'], unique=True)
    op.create_index(op.f('ix_instances_id'), 'instances', ['id'], unique=False)
    op.create_index(op.f('ix_instances_slug'), 'instances', ['slug'], unique=True)
    op.create_table('instance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instance_events_id'), 'instance_events', ['id'], unique=False)
    op.create_index(op.f('ix_instance_events_instance_id'), 'instance_events', ['instance_id'], unique=False)
    op.create_table('instance_stats_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=True),
    sa.Column('map_bounds_coarse', sa.String(length=100), nullable=True),
    sa.Column('last_data_refresh_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('software_version', sa.String(length=100), nullable=True),
    sa.Column('payload_received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instance_stats_snapshots_id'), 'instance_stats_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_instance_stats_snapshots_instance_id'), 'instance_stats_snapshots', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instance_stats_snapshots_instance_id'), table_name='instance_stats_snapshots')
    op.drop_index(op.f('ix_instance_stats_snapshots_id'), table_name='instance_stats_snapshots')
    op.drop_table('instance_stats_snapshots')
    op.drop_index(op.f('ix_instance_events_instance_id'), table_name='instance_events')
    op.drop_index(op.f('ix_instance_events_id'), table_name='instance_events')
    op.drop_table('instance_events')
    op.drop_index(op.f('ix_instances_slug'), table_name='instances')
    op.drop_index(op.f('ix_instances_id'), table_name='instances')
    op.drop_index(op.f('ix_instances_canonical_url'), table_name='instances')
    op.drop_table('instances')
    # ### end Alembic commands ###
